; Truc pour Krusty, AKG format, v1.0.

; Generated by Arkos Tracker 3.

Start
StartDisarkGenerateExternalLabel
DisarkByteRegionStart0
    db "AT30"
DisarkPointerRegionStart1
    dw ArpeggioTable    ; The address of the Arpeggio table.
    dw PitchTable    ; The address of the Pitch table.
    dw InstrumentTable    ; The address of the Instrument table.
    dw EffectBlockTable    ; The address of the Effect Block table.
DisarkPointerRegionEnd1


; The addresses of each Subsong.
DisarkPointerRegionStart2
    dw Subsong0_Start
DisarkPointerRegionEnd2

; Declares all the Arpeggios.
ArpeggioTable
DisarkPointerRegionStart3
    dw Arpeggio1
    dw Arpeggio2
    dw Arpeggio3
    dw Arpeggio4
    dw Arpeggio5
    dw Arpeggio6
    dw Arpeggio7
DisarkPointerRegionEnd3
Arpeggio1
    db 1    ; The speed.

    db 0
    db 5
    db 9
    db -128
DisarkWordForceReference4
    dw Arpeggio1 + 0 + 1    ; Loop.

Arpeggio2
    db 1    ; The speed.

    db 0
    db 4
    db 7
    db -128
DisarkWordForceReference5
    dw Arpeggio2 + 0 + 1    ; Loop.

Arpeggio3
    db 1    ; The speed.

    db 0
    db 3
    db 7
    db -128
DisarkWordForceReference6
    dw Arpeggio3 + 0 + 1    ; Loop.

Arpeggio4
    db 1    ; The speed.

    db 0
    db 5
    db -128
DisarkWordForceReference7
    dw Arpeggio4 + 0 + 1    ; Loop.

Arpeggio5
    db 1    ; The speed.

    db 0
    db 4
    db -128
DisarkWordForceReference8
    dw Arpeggio5 + 0 + 1    ; Loop.

Arpeggio6
    db 1    ; The speed.

    db 0
    db 3
    db -128
DisarkWordForceReference9
    dw Arpeggio6 + 0 + 1    ; Loop.

Arpeggio7
    db 1    ; The speed.

    db 12
    db 0
    db -128
DisarkWordForceReference10
    dw Arpeggio7 + 1 + 1    ; Loop.


; Declares all the Pitches.
PitchTable
DisarkPointerRegionStart11
DisarkPointerRegionEnd11

; Declares all the Instruments.
InstrumentTable
DisarkPointerRegionStart12
    dw EmptyInstrument
    dw Instrument1
    dw Instrument2
    dw Instrument3
    dw Instrument4
    dw Instrument5
    dw Instrument6
DisarkPointerRegionEnd12

EmptyInstrument
    db 0    ; The speed (>0, 0 for 256).

    db 0    ; No Soft no Hard. Volume: 0. Noise? false.

    db 6    ; Loop to silence.

Instrument1
    db 1    ; The speed (>0, 0 for 256).

    db 121    ; Soft only. Volume: 15.
    db 1    ; Additional data. Noise: 1. Pitch? false. Arp? false. Period? false.

    db 241    ; Soft only. Volume: 14. Volume only.

    db 233    ; Soft only. Volume: 13. Volume only.

    db 225    ; Soft only. Volume: 12. Volume only.

    db 217    ; Soft only. Volume: 11. Volume only.

    db 209    ; Soft only. Volume: 10. Volume only.

    db 201    ; Soft only. Volume: 9. Volume only.

    db 193    ; Soft only. Volume: 8. Volume only.

    db 185    ; Soft only. Volume: 7. Volume only.

    db 177    ; Soft only. Volume: 6. Volume only.

    db 169    ; Soft only. Volume: 5. Volume only.

    db 161    ; Soft only. Volume: 4. Volume only.

    db 153    ; Soft only. Volume: 3. Volume only.

    db 145    ; Soft only. Volume: 2. Volume only.

    db 137    ; Soft only. Volume: 1. Volume only.

    db 6    ; Loop to silence.

Instrument2
    db 1    ; The speed (>0, 0 for 256).

    db 249    ; Soft only. Volume: 15. Volume only.

    db 241    ; Soft only. Volume: 14. Volume only.

    db 233    ; Soft only. Volume: 13. Volume only.

    db 225    ; Soft only. Volume: 12. Volume only.

    db 217    ; Soft only. Volume: 11. Volume only.

    db 209    ; Soft only. Volume: 10. Volume only.

    db 201    ; Soft only. Volume: 9. Volume only.

    db 193    ; Soft only. Volume: 8. Volume only.

    db 185    ; Soft only. Volume: 7. Volume only.

    db 177    ; Soft only. Volume: 6. Volume only.

    db 169    ; Soft only. Volume: 5. Volume only.

    db 161    ; Soft only. Volume: 4. Volume only.

    db 153    ; Soft only. Volume: 3. Volume only.

    db 145    ; Soft only. Volume: 2. Volume only.

    db 137    ; Soft only. Volume: 1. Volume only.

    db 6    ; Loop to silence.

Instrument3
    db 2    ; The speed (>0, 0 for 256).

    db 249    ; Soft only. Volume: 15. Volume only.

    db 241    ; Soft only. Volume: 14. Volume only.

    db 233    ; Soft only. Volume: 13. Volume only.

    db 225    ; Soft only. Volume: 12. Volume only.

Instrument3_Loop
    db 225    ; Soft only. Volume: 12. Volume only.

    db 225    ; Soft only. Volume: 12. Volume only.

    db 89    ; Soft only. Volume: 11.
    db 32    ; Additional data. Noise: 0. Pitch? true. Arp? false. Period? false.
    dw -1    ; Pitch.

    db 89    ; Soft only. Volume: 11.
    db 32    ; Additional data. Noise: 0. Pitch? true. Arp? false. Period? false.
    dw -1    ; Pitch.

    db 97    ; Soft only. Volume: 12.
    db 32    ; Additional data. Noise: 0. Pitch? true. Arp? false. Period? false.
    dw -1    ; Pitch.

    db 233    ; Soft only. Volume: 13. Volume only.

    db 7    ; Loop.
DisarkWordForceReference13
    dw Instrument3_Loop    ; Loop here.

Instrument4
    db 2    ; The speed (>0, 0 for 256).

    db 249    ; Soft only. Volume: 15. Volume only.

    db 241    ; Soft only. Volume: 14. Volume only.

    db 233    ; Soft only. Volume: 13. Volume only.

Instrument4_Loop
    db 225    ; Soft only. Volume: 12. Volume only.

    db 7    ; Loop.
DisarkWordForceReference14
    dw Instrument4_Loop    ; Loop here.

Instrument5
    db 3    ; The speed (>0, 0 for 256).

    db 225    ; Soft only. Volume: 12. Volume only.

    db 217    ; Soft only. Volume: 11. Volume only.

    db 209    ; Soft only. Volume: 10. Volume only.

    db 201    ; Soft only. Volume: 9. Volume only.

    db 193    ; Soft only. Volume: 8. Volume only.

    db 185    ; Soft only. Volume: 7. Volume only.

    db 177    ; Soft only. Volume: 6. Volume only.

    db 169    ; Soft only. Volume: 5. Volume only.

    db 161    ; Soft only. Volume: 4. Volume only.

    db 153    ; Soft only. Volume: 3. Volume only.

    db 145    ; Soft only. Volume: 2. Volume only.

    db 6    ; Loop to silence.

Instrument6
    db 2    ; The speed (>0, 0 for 256).

    db 225    ; Soft only. Volume: 12. Volume only.

    db 233    ; Soft only. Volume: 13. Volume only.

    db 241    ; Soft only. Volume: 14. Volume only.

    db 249    ; Soft only. Volume: 15. Volume only.

    db 241    ; Soft only. Volume: 14. Volume only.

    db 233    ; Soft only. Volume: 13. Volume only.

Instrument6_Loop
    db 217    ; Soft only. Volume: 11. Volume only.

    db 217    ; Soft only. Volume: 11. Volume only.

    db 217    ; Soft only. Volume: 11. Volume only.

    db 209    ; Soft only. Volume: 10. Volume only.

    db 209    ; Soft only. Volume: 10. Volume only.

    db 209    ; Soft only. Volume: 10. Volume only.

    db 7    ; Loop.
DisarkWordForceReference15
    dw Instrument6_Loop    ; Loop here.


; The indexes of the effect blocks used by this song.
EffectBlockTable
DisarkPointerRegionStart16
    dw EffectBlock_P4P2    ; Index 0
    dw EffectBlock_P4P0    ; Index 1
    dw EffectBlock_P5P7P8    ; Index 2
    dw EffectBlock_P4P1    ; Index 3
    dw EffectBlock_P5P0P6P1    ; Index 4
    dw EffectBlock_P4P3    ; Index 5
    dw EffectBlock_P5P0P6P0    ; Index 6
    dw EffectBlock_P5P4P6P4    ; Index 7
    dw EffectBlock_P5P0P6P2    ; Index 8
    dw EffectBlock_P5P4P6P3    ; Index 9
    dw EffectBlock_P5P4P6P5    ; Index 10
    dw EffectBlock_P24P52P0P4    ; Index 11
    dw EffectBlock_P4P4    ; Index 12
    dw EffectBlock_P4P5    ; Index 13
    dw EffectBlock_P4P7    ; Index 14
    dw EffectBlock_P24P57P0P3    ; Index 15
    dw EffectBlock_P5P2P6P6    ; Index 16
    dw EffectBlock_P4P6    ; Index 17
    dw EffectBlock_P4P11    ; Index 18
    dw EffectBlock_P4P14    ; Index 19
    dw EffectBlock_P24P64P0P3    ; Index 20
    dw EffectBlock_P24P64P0P1    ; Index 21
    dw EffectBlock_P8    ; Index 22
    dw EffectBlock_P24P69P0P1    ; Index 23
    dw EffectBlock_P4P8    ; Index 24
    dw EffectBlock_P4P9    ; Index 25
    dw EffectBlock_P4P10    ; Index 26
    dw EffectBlock_P4P12    ; Index 27
    dw EffectBlock_P4P13    ; Index 28
    dw EffectBlock_P4P15    ; Index 29
    dw EffectBlock_P5P0P8    ; Index 30
    dw EffectBlock_P6P1    ; Index 31
DisarkPointerRegionEnd16
EffectBlock_P5P0P6P0
    db 5
    db 0
    db 6
    db 0

EffectBlock_P5P7P8
    db 5
    db 7
    db 8

EffectBlock_P5P4P6P3
    db 5
    db 4
    db 6
    db 3

EffectBlock_P5P0P6P1
    db 5
    db 0
    db 6
    db 1

EffectBlock_P5P4P6P4
    db 5
    db 4
    db 6
    db 4

EffectBlock_P5P0P6P2
    db 5
    db 0
    db 6
    db 2

EffectBlock_P5P4P6P5
    db 5
    db 4
    db 6
    db 5

EffectBlock_P5P0P8
    db 5
    db 0
    db 8

EffectBlock_P4P1
    db 4
    db 1

EffectBlock_P4P2
    db 4
    db 2

EffectBlock_P4P3
    db 4
    db 3

EffectBlock_P4P0
    db 4
    db 0

EffectBlock_P24P52P0P4
    db 24
    db 52
    db 0
    db 4

EffectBlock_P4P4
    db 4
    db 4

EffectBlock_P4P5
    db 4
    db 5

EffectBlock_P4P6
    db 4
    db 6

EffectBlock_P4P7
    db 4
    db 7

EffectBlock_P24P64P0P3
    db 24
    db 64
    db 0
    db 3

EffectBlock_P24P57P0P3
    db 24
    db 57
    db 0
    db 3

EffectBlock_P24P64P0P1
    db 24
    db 64
    db 0
    db 1

EffectBlock_P8
    db 8

EffectBlock_P6P1
    db 6
    db 1

EffectBlock_P5P2P6P6
    db 5
    db 2
    db 6
    db 6

EffectBlock_P4P11
    db 4
    db 11

EffectBlock_P4P14
    db 4
    db 14

EffectBlock_P24P69P0P1
    db 24
    db 69
    db 0
    db 1

EffectBlock_P4P8
    db 4
    db 8

EffectBlock_P4P9
    db 4
    db 9

EffectBlock_P4P10
    db 4
    db 10

EffectBlock_P4P12
    db 4
    db 12

EffectBlock_P4P13
    db 4
    db 13

EffectBlock_P4P15
    db 4
    db 15


DisarkByteRegionEnd0

; Subsong 0
; ----------------------
Subsong0_DisarkByteRegionStart0
Subsong0_Start
    db 2    ; ReplayFrequency (0=12.5hz, 1=25hz, 2=50hz, 3=100hz, 4=150hz, 5=300hz).
    db 1    ; Digichannel (>=0).
    db 1    ; PSG count (>0).
    db 2    ; Loop start index (>=0).
    db 17    ; End index (>=0).
    db 5    ; Initial speed (>=0).
    db 22    ; Base note index (>=0).

Subsong0_Linker
Subsong0_DisarkPointerRegionStart1
; Position 0
    dw Subsong0_Track0
    dw Subsong0_Track0
    dw Subsong0_Track1
    dw Subsong0_LinkerBlock0
; Position 1
    dw Subsong0_Track0
    dw Subsong0_Track0
    dw Subsong0_Track2
    dw Subsong0_LinkerBlock0
; Position 2
Subsong0_Linker_Loop
    dw Subsong0_Track3
    dw Subsong0_Track4
    dw Subsong0_Track1
    dw Subsong0_LinkerBlock0
; Position 3
    dw Subsong0_Track5
    dw Subsong0_Track6
    dw Subsong0_Track2
    dw Subsong0_LinkerBlock0
; Position 4
    dw Subsong0_Track7
    dw Subsong0_Track4
    dw Subsong0_Track1
    dw Subsong0_LinkerBlock0
; Position 5
    dw Subsong0_Track8
    dw Subsong0_Track9
    dw Subsong0_Track2
    dw Subsong0_LinkerBlock0
; Position 6
    dw Subsong0_Track3
    dw Subsong0_Track4
    dw Subsong0_Track1
    dw Subsong0_LinkerBlock0
; Position 7
    dw Subsong0_Track5
    dw Subsong0_Track6
    dw Subsong0_Track2
    dw Subsong0_LinkerBlock0
; Position 8
    dw Subsong0_Track10
    dw Subsong0_Track4
    dw Subsong0_Track1
    dw Subsong0_LinkerBlock0
; Position 9
    dw Subsong0_Track11
    dw Subsong0_Track9
    dw Subsong0_Track2
    dw Subsong0_LinkerBlock0
; Position 10
    dw Subsong0_Track12
    dw Subsong0_Track4
    dw Subsong0_Track13
    dw Subsong0_LinkerBlock0
; Position 11
    dw Subsong0_Track14
    dw Subsong0_Track15
    dw Subsong0_Track16
    dw Subsong0_LinkerBlock0
; Position 12
    dw Subsong0_Track17
    dw Subsong0_Track4
    dw Subsong0_Track13
    dw Subsong0_LinkerBlock0
; Position 13
    dw Subsong0_Track18
    dw Subsong0_Track15
    dw Subsong0_Track16
    dw Subsong0_LinkerBlock0
; Position 14
    dw Subsong0_Track12
    dw Subsong0_Track4
    dw Subsong0_Track13
    dw Subsong0_LinkerBlock0
; Position 15
    dw Subsong0_Track14
    dw Subsong0_Track15
    dw Subsong0_Track16
    dw Subsong0_LinkerBlock0
; Position 16
    dw Subsong0_Track19
    dw Subsong0_Track4
    dw Subsong0_Track13
    dw Subsong0_LinkerBlock0
; Position 17
    dw Subsong0_Track20
    dw Subsong0_Track15
    dw Subsong0_Track16
    dw Subsong0_LinkerBlock0
Subsong0_DisarkPointerRegionEnd1
    dw 0    ; Loop.
Subsong0_DisarkWordForceReference2
    dw Subsong0_Linker_Loop

Subsong0_LinkerBlock0
    db 64    ; Height.
    db 0    ; Transposition 0.
    db 0    ; Transposition 1.
    db 0    ; Transposition 2.
Subsong0_DisarkWordForceReference3
    dw Subsong0_SpeedTrack0    ; SpeedTrack address.
Subsong0_DisarkWordForceReference4
    dw Subsong0_EventTrack0    ; EventTrack address.


Subsong0_Track0
    db 61
    db 127    ; Waits for 128 lines.


Subsong0_Track1
    db 218
    db 1    ; New Instrument (1).
    db 6    ; Index to an effect block.
    db 60    ; Waits for 1 line.

    db 90
    db 2    ; Index to an effect block.
    db 60    ; Waits for 1 line.

    db 90
    db 9    ; Index to an effect block.
    db 60    ; Waits for 1 line.

    db 90
    db 6    ; Index to an effect block.
    db 60    ; Waits for 1 line.

    db 90
    db 2    ; Index to an effect block.
    db 60    ; Waits for 1 line.

    db 90
    db 9    ; Index to an effect block.
    db 60    ; Waits for 1 line.

    db 90
    db 6    ; Index to an effect block.
    db 60    ; Waits for 1 line.

    db 90
    db 2    ; Index to an effect block.
    db 60    ; Waits for 1 line.

    db 90
    db 6    ; Index to an effect block.
    db 60    ; Waits for 1 line.

    db 90
    db 2    ; Index to an effect block.
    db 60    ; Waits for 1 line.

    db 90
    db 9    ; Index to an effect block.
    db 60    ; Waits for 1 line.

    db 90
    db 6    ; Index to an effect block.
    db 60    ; Waits for 1 line.

    db 90
    db 2    ; Index to an effect block.
    db 60    ; Waits for 1 line.

    db 90
    db 9    ; Index to an effect block.
    db 60    ; Waits for 1 line.

    db 90
    db 6    ; Index to an effect block.
    db 60    ; Waits for 1 line.

    db 90
    db 2    ; Index to an effect block.
    db 60    ; Waits for 1 line.

    db 90
    db 4    ; Index to an effect block.
    db 60    ; Waits for 1 line.

    db 90
    db 2    ; Index to an effect block.
    db 60    ; Waits for 1 line.

    db 90
    db 7    ; Index to an effect block.
    db 60    ; Waits for 1 line.

    db 90
    db 4    ; Index to an effect block.
    db 60    ; Waits for 1 line.

    db 90
    db 2    ; Index to an effect block.
    db 60    ; Waits for 1 line.

    db 90
    db 7    ; Index to an effect block.
    db 60    ; Waits for 1 line.

    db 90
    db 4    ; Index to an effect block.
    db 60    ; Waits for 1 line.

    db 90
    db 2    ; Index to an effect block.
    db 60    ; Waits for 1 line.

    db 90
    db 4    ; Index to an effect block.
    db 60    ; Waits for 1 line.

    db 90
    db 2    ; Index to an effect block.
    db 60    ; Waits for 1 line.

    db 90
    db 7    ; Index to an effect block.
    db 60    ; Waits for 1 line.

    db 90
    db 4    ; Index to an effect block.
    db 60    ; Waits for 1 line.

    db 90
    db 2    ; Index to an effect block.
    db 60    ; Waits for 1 line.

    db 90
    db 7    ; Index to an effect block.
    db 60    ; Waits for 1 line.

    db 90
    db 4    ; Index to an effect block.
    db 60    ; Waits for 1 line.

    db 90
    db 2    ; Index to an effect block.
    db 61
    db 127    ; Waits for 128 lines.


Subsong0_Track2
    db 220
    db 1    ; New Instrument (1).
    db 8    ; Index to an effect block.
    db 60    ; Waits for 1 line.

    db 92
    db 2    ; Index to an effect block.
    db 60    ; Waits for 1 line.

    db 92
    db 10    ; Index to an effect block.
    db 60    ; Waits for 1 line.

    db 92
    db 8    ; Index to an effect block.
    db 60    ; Waits for 1 line.

    db 92
    db 2    ; Index to an effect block.
    db 60    ; Waits for 1 line.

    db 92
    db 10    ; Index to an effect block.
    db 60    ; Waits for 1 line.

    db 92
    db 8    ; Index to an effect block.
    db 60    ; Waits for 1 line.

    db 92
    db 2    ; Index to an effect block.
    db 60    ; Waits for 1 line.

    db 92
    db 8    ; Index to an effect block.
    db 60    ; Waits for 1 line.

    db 92
    db 2    ; Index to an effect block.
    db 60    ; Waits for 1 line.

    db 92
    db 10    ; Index to an effect block.
    db 60    ; Waits for 1 line.

    db 92
    db 8    ; Index to an effect block.
    db 60    ; Waits for 1 line.

    db 92
    db 2    ; Index to an effect block.
    db 60    ; Waits for 1 line.

    db 92
    db 10    ; Index to an effect block.
    db 60    ; Waits for 1 line.

    db 92
    db 8    ; Index to an effect block.
    db 60    ; Waits for 1 line.

    db 92
    db 2    ; Index to an effect block.
    db 60    ; Waits for 1 line.

    db 88
    db 4    ; Index to an effect block.
    db 60    ; Waits for 1 line.

    db 88
    db 2    ; Index to an effect block.
    db 60    ; Waits for 1 line.

    db 88
    db 7    ; Index to an effect block.
    db 60    ; Waits for 1 line.

    db 88
    db 4    ; Index to an effect block.
    db 60    ; Waits for 1 line.

    db 88
    db 2    ; Index to an effect block.
    db 60    ; Waits for 1 line.

    db 88
    db 7    ; Index to an effect block.
    db 60    ; Waits for 1 line.

    db 88
    db 4    ; Index to an effect block.
    db 60    ; Waits for 1 line.

    db 88
    db 2    ; Index to an effect block.
    db 60    ; Waits for 1 line.

    db 88
    db 4    ; Index to an effect block.
    db 60    ; Waits for 1 line.

    db 88
    db 2    ; Index to an effect block.
    db 60    ; Waits for 1 line.

    db 88
    db 7    ; Index to an effect block.
    db 60    ; Waits for 1 line.

    db 88
    db 4    ; Index to an effect block.
    db 60    ; Waits for 1 line.

    db 88
    db 2    ; Index to an effect block.
    db 60    ; Waits for 1 line.

    db 88
    db 7    ; Index to an effect block.
    db 60    ; Waits for 1 line.

    db 88
    db 4    ; Index to an effect block.
    db 60    ; Waits for 1 line.

    db 88
    db 2    ; Index to an effect block.
    db 61
    db 127    ; Waits for 128 lines.


Subsong0_Track3
    db 227
    db 3    ; New Instrument (3).
    db 30    ; Index to an effect block.
    db 62 + 3 * 64    ; Optimized wait for 5 lines.

    db 99
    db 3    ; Index to an effect block.
    db 62 + 3 * 64    ; Optimized wait for 5 lines.

    db 99
    db 0    ; Index to an effect block.
    db 62 + 3 * 64    ; Optimized wait for 5 lines.

    db 99
    db 5    ; Index to an effect block.
    db 62 + 2 * 64    ; Optimized wait for 4 lines.

    db 192
    db 0    ; New Instrument (0).
    db 1    ; Index to an effect block.
    db 166
    db 3    ; New Instrument (3).
    db 62 + 3 * 64    ; Optimized wait for 5 lines.

    db 124    ; No note, but effects.
    db 11    ; Index to an effect block.
    db 60    ; Waits for 1 line.

    db 30
    db 62 + 3 * 64    ; Optimized wait for 5 lines.

    db 94
    db 3    ; Index to an effect block.
    db 62 + 3 * 64    ; Optimized wait for 5 lines.

    db 94
    db 0    ; Index to an effect block.
    db 62 + 3 * 64    ; Optimized wait for 5 lines.

    db 94
    db 5    ; Index to an effect block.
    db 62 + 2 * 64    ; Optimized wait for 4 lines.

    db 192
    db 0    ; New Instrument (0).
    db 1    ; Index to an effect block.
    db 159
    db 3    ; New Instrument (3).
    db 61
    db 127    ; Waits for 128 lines.


Subsong0_Track4
    db 135
    db 4    ; New Instrument (4).
    db 61
    db 12    ; Waits for 13 lines.

    db 135
    db 5    ; New Instrument (5).
    db 61
    db 12    ; Waits for 13 lines.

    db 142
    db 4    ; New Instrument (4).
    db 62 + 0 * 64    ; Optimized wait for 2 lines.

    db 142
    db 5    ; New Instrument (5).
    db 130
    db 4    ; New Instrument (4).
    db 61
    db 12    ; Waits for 13 lines.

    db 130
    db 5    ; New Instrument (5).
    db 61
    db 127    ; Waits for 128 lines.


Subsong0_Track5
    db 225
    db 3    ; New Instrument (3).
    db 1    ; Index to an effect block.
    db 62 + 3 * 64    ; Optimized wait for 5 lines.

    db 97
    db 3    ; Index to an effect block.
    db 62 + 3 * 64    ; Optimized wait for 5 lines.

    db 97
    db 0    ; Index to an effect block.
    db 62 + 1 * 64    ; Optimized wait for 3 lines.

    db 99
    db 1    ; Index to an effect block.
    db 62 + 3 * 64    ; Optimized wait for 5 lines.

    db 99
    db 3    ; Index to an effect block.
    db 62 + 3 * 64    ; Optimized wait for 5 lines.

    db 99
    db 0    ; Index to an effect block.
    db 62 + 1 * 64    ; Optimized wait for 3 lines.

    db 124    ; No note, but effects.
    db 5    ; Index to an effect block.
    db 124    ; No note, but effects.
    db 12    ; Index to an effect block.
    db 124    ; No note, but effects.
    db 13    ; Index to an effect block.
    db 124    ; No note, but effects.
    db 17    ; Index to an effect block.
    db 124    ; No note, but effects.
    db 14    ; Index to an effect block.
    db 128
    db 0    ; New Instrument (0).
    db 61
    db 127    ; Waits for 128 lines.


Subsong0_Track6
    db 132
    db 4    ; New Instrument (4).
    db 61
    db 12    ; Waits for 13 lines.

    db 132
    db 5    ; New Instrument (5).
    db 61
    db 127    ; Waits for 128 lines.


Subsong0_Track7
    db 227
    db 3    ; New Instrument (3).
    db 1    ; Index to an effect block.
    db 62 + 3 * 64    ; Optimized wait for 5 lines.

    db 99
    db 3    ; Index to an effect block.
    db 62 + 3 * 64    ; Optimized wait for 5 lines.

    db 99
    db 0    ; Index to an effect block.
    db 62 + 3 * 64    ; Optimized wait for 5 lines.

    db 99
    db 5    ; Index to an effect block.
    db 62 + 2 * 64    ; Optimized wait for 4 lines.

    db 192
    db 0    ; New Instrument (0).
    db 1    ; Index to an effect block.
    db 166
    db 3    ; New Instrument (3).
    db 62 + 3 * 64    ; Optimized wait for 5 lines.

    db 124    ; No note, but effects.
    db 20    ; Index to an effect block.
    db 60    ; Waits for 1 line.

    db 42
    db 62 + 3 * 64    ; Optimized wait for 5 lines.

    db 106
    db 3    ; Index to an effect block.
    db 62 + 3 * 64    ; Optimized wait for 5 lines.

    db 106
    db 0    ; Index to an effect block.
    db 62 + 3 * 64    ; Optimized wait for 5 lines.

    db 106
    db 5    ; Index to an effect block.
    db 62 + 2 * 64    ; Optimized wait for 4 lines.

    db 192
    db 0    ; New Instrument (0).
    db 1    ; Index to an effect block.
    db 166
    db 3    ; New Instrument (3).
    db 61
    db 127    ; Waits for 128 lines.


Subsong0_Track8
    db 232
    db 3    ; New Instrument (3).
    db 1    ; Index to an effect block.
    db 62 + 3 * 64    ; Optimized wait for 5 lines.

    db 104
    db 3    ; Index to an effect block.
    db 62 + 3 * 64    ; Optimized wait for 5 lines.

    db 104
    db 0    ; Index to an effect block.
    db 62 + 3 * 64    ; Optimized wait for 5 lines.

    db 104
    db 5    ; Index to an effect block.
    db 62 + 3 * 64    ; Optimized wait for 5 lines.

    db 107
    db 1    ; Index to an effect block.
    db 62 + 3 * 64    ; Optimized wait for 5 lines.

    db 124    ; No note, but effects.
    db 15    ; Index to an effect block.
    db 60    ; Waits for 1 line.

    db 99
    db 1    ; Index to an effect block.
    db 61
    db 11    ; Waits for 12 lines.

    db 124    ; No note, but effects.
    db 3    ; Index to an effect block.
    db 124    ; No note, but effects.
    db 0    ; Index to an effect block.
    db 124    ; No note, but effects.
    db 5    ; Index to an effect block.
    db 95
    db 1    ; Index to an effect block.
    db 61
    db 6    ; Waits for 7 lines.

    db 33
    db 61
    db 127    ; Waits for 128 lines.


Subsong0_Track9
    db 132
    db 4    ; New Instrument (4).
    db 61
    db 12    ; Waits for 13 lines.

    db 132
    db 5    ; New Instrument (5).
    db 61
    db 16    ; Waits for 17 lines.

    db 223
    db 3    ; New Instrument (3).
    db 3    ; Index to an effect block.
    db 61
    db 11    ; Waits for 12 lines.

    db 124    ; No note, but effects.
    db 0    ; Index to an effect block.
    db 124    ; No note, but effects.
    db 5    ; Index to an effect block.
    db 124    ; No note, but effects.
    db 12    ; Index to an effect block.
    db 192
    db 0    ; New Instrument (0).
    db 1    ; Index to an effect block.
    db 61
    db 127    ; Waits for 128 lines.


Subsong0_Track10
    db 227
    db 3    ; New Instrument (3).
    db 1    ; Index to an effect block.
    db 62 + 3 * 64    ; Optimized wait for 5 lines.

    db 99
    db 3    ; Index to an effect block.
    db 62 + 3 * 64    ; Optimized wait for 5 lines.

    db 99
    db 0    ; Index to an effect block.
    db 62 + 3 * 64    ; Optimized wait for 5 lines.

    db 99
    db 5    ; Index to an effect block.
    db 62 + 2 * 64    ; Optimized wait for 4 lines.

    db 192
    db 0    ; New Instrument (0).
    db 1    ; Index to an effect block.
    db 171
    db 3    ; New Instrument (3).
    db 62 + 3 * 64    ; Optimized wait for 5 lines.

    db 124    ; No note, but effects.
    db 21    ; Index to an effect block.
    db 60    ; Waits for 1 line.

    db 42
    db 62 + 3 * 64    ; Optimized wait for 5 lines.

    db 106
    db 3    ; Index to an effect block.
    db 62 + 3 * 64    ; Optimized wait for 5 lines.

    db 106
    db 0    ; Index to an effect block.
    db 62 + 3 * 64    ; Optimized wait for 5 lines.

    db 106
    db 5    ; Index to an effect block.
    db 62 + 2 * 64    ; Optimized wait for 4 lines.

    db 192
    db 0    ; New Instrument (0).
    db 1    ; Index to an effect block.
    db 166
    db 3    ; New Instrument (3).
    db 61
    db 127    ; Waits for 128 lines.


Subsong0_Track11
    db 232
    db 3    ; New Instrument (3).
    db 1    ; Index to an effect block.
    db 62 + 3 * 64    ; Optimized wait for 5 lines.

    db 104
    db 3    ; Index to an effect block.
    db 62 + 3 * 64    ; Optimized wait for 5 lines.

    db 104
    db 0    ; Index to an effect block.
    db 62 + 3 * 64    ; Optimized wait for 5 lines.

    db 104
    db 5    ; Index to an effect block.
    db 62 + 3 * 64    ; Optimized wait for 5 lines.

    db 107
    db 1    ; Index to an effect block.
    db 62 + 3 * 64    ; Optimized wait for 5 lines.

    db 124    ; No note, but effects.
    db 15    ; Index to an effect block.
    db 60    ; Waits for 1 line.

    db 99
    db 1    ; Index to an effect block.
    db 61
    db 11    ; Waits for 12 lines.

    db 124    ; No note, but effects.
    db 3    ; Index to an effect block.
    db 124    ; No note, but effects.
    db 0    ; Index to an effect block.
    db 124    ; No note, but effects.
    db 5    ; Index to an effect block.
    db 95
    db 1    ; Index to an effect block.
    db 61
    db 6    ; Waits for 7 lines.

    db 38
    db 61
    db 127    ; Waits for 128 lines.


Subsong0_Track12
    db 218
    db 3    ; New Instrument (3).
    db 6    ; Index to an effect block.
    db 62 + 3 * 64    ; Optimized wait for 5 lines.

    db 90
    db 3    ; Index to an effect block.
    db 62 + 3 * 64    ; Optimized wait for 5 lines.

    db 90
    db 0    ; Index to an effect block.
    db 62 + 3 * 64    ; Optimized wait for 5 lines.

    db 90
    db 5    ; Index to an effect block.
    db 62 + 2 * 64    ; Optimized wait for 4 lines.

    db 192
    db 0    ; New Instrument (0).
    db 1    ; Index to an effect block.
    db 230
    db 3    ; New Instrument (3).
    db 22    ; Index to an effect block.
    db 62 + 3 * 64    ; Optimized wait for 5 lines.

    db 124    ; No note, but effects.
    db 11    ; Index to an effect block.
    db 60    ; Waits for 1 line.

    db 90
    db 31    ; Index to an effect block.
    db 62 + 3 * 64    ; Optimized wait for 5 lines.

    db 90
    db 3    ; Index to an effect block.
    db 62 + 3 * 64    ; Optimized wait for 5 lines.

    db 90
    db 0    ; Index to an effect block.
    db 62 + 3 * 64    ; Optimized wait for 5 lines.

    db 90
    db 5    ; Index to an effect block.
    db 62 + 2 * 64    ; Optimized wait for 4 lines.

    db 192
    db 0    ; New Instrument (0).
    db 1    ; Index to an effect block.
    db 223
    db 3    ; New Instrument (3).
    db 22    ; Index to an effect block.
    db 61
    db 127    ; Waits for 128 lines.


Subsong0_Track13
    db 218
    db 1    ; New Instrument (1).
    db 16    ; Index to an effect block.
    db 60    ; Waits for 1 line.

    db 223
    db 2    ; New Instrument (2).
    db 0    ; Index to an effect block.
    db 60    ; Waits for 1 line.

    db 227
    db 1    ; New Instrument (1).
    db 3    ; Index to an effect block.
    db 60    ; Waits for 1 line.

    db 102
    db 1    ; Index to an effect block.
    db 60    ; Waits for 1 line.

    db 218
    db 2    ; New Instrument (2).
    db 0    ; Index to an effect block.
    db 60    ; Waits for 1 line.

    db 95
    db 0    ; Index to an effect block.
    db 60    ; Waits for 1 line.

    db 227
    db 1    ; New Instrument (1).
    db 3    ; Index to an effect block.
    db 60    ; Waits for 1 line.

    db 102
    db 1    ; Index to an effect block.
    db 60    ; Waits for 1 line.

    db 218
    db 2    ; New Instrument (2).
    db 0    ; Index to an effect block.
    db 60    ; Waits for 1 line.

    db 95
    db 0    ; Index to an effect block.
    db 60    ; Waits for 1 line.

    db 227
    db 1    ; New Instrument (1).
    db 3    ; Index to an effect block.
    db 60    ; Waits for 1 line.

    db 102
    db 1    ; Index to an effect block.
    db 60    ; Waits for 1 line.

    db 218
    db 2    ; New Instrument (2).
    db 0    ; Index to an effect block.
    db 60    ; Waits for 1 line.

    db 95
    db 0    ; Index to an effect block.
    db 60    ; Waits for 1 line.

    db 227
    db 1    ; New Instrument (1).
    db 3    ; Index to an effect block.
    db 60    ; Waits for 1 line.

    db 102
    db 1    ; Index to an effect block.
    db 60    ; Waits for 1 line.

    db 222
    db 2    ; New Instrument (2).
    db 0    ; Index to an effect block.
    db 60    ; Waits for 1 line.

    db 97
    db 0    ; Index to an effect block.
    db 60    ; Waits for 1 line.

    db 230
    db 1    ; New Instrument (1).
    db 3    ; Index to an effect block.
    db 60    ; Waits for 1 line.

    db 106
    db 1    ; Index to an effect block.
    db 60    ; Waits for 1 line.

    db 222
    db 2    ; New Instrument (2).
    db 0    ; Index to an effect block.
    db 60    ; Waits for 1 line.

    db 97
    db 0    ; Index to an effect block.
    db 60    ; Waits for 1 line.

    db 230
    db 1    ; New Instrument (1).
    db 3    ; Index to an effect block.
    db 60    ; Waits for 1 line.

    db 106
    db 1    ; Index to an effect block.
    db 60    ; Waits for 1 line.

    db 222
    db 2    ; New Instrument (2).
    db 0    ; Index to an effect block.
    db 60    ; Waits for 1 line.

    db 97
    db 0    ; Index to an effect block.
    db 60    ; Waits for 1 line.

    db 230
    db 1    ; New Instrument (1).
    db 3    ; Index to an effect block.
    db 60    ; Waits for 1 line.

    db 106
    db 1    ; Index to an effect block.
    db 60    ; Waits for 1 line.

    db 222
    db 2    ; New Instrument (2).
    db 0    ; Index to an effect block.
    db 60    ; Waits for 1 line.

    db 97
    db 0    ; Index to an effect block.
    db 60    ; Waits for 1 line.

    db 230
    db 1    ; New Instrument (1).
    db 3    ; Index to an effect block.
    db 60    ; Waits for 1 line.

    db 106
    db 1    ; Index to an effect block.
    db 61
    db 127    ; Waits for 128 lines.


Subsong0_Track14
    db 220
    db 3    ; New Instrument (3).
    db 8    ; Index to an effect block.
    db 62 + 3 * 64    ; Optimized wait for 5 lines.

    db 92
    db 3    ; Index to an effect block.
    db 62 + 3 * 64    ; Optimized wait for 5 lines.

    db 92
    db 0    ; Index to an effect block.
    db 62 + 1 * 64    ; Optimized wait for 3 lines.

    db 88
    db 4    ; Index to an effect block.
    db 62 + 3 * 64    ; Optimized wait for 5 lines.

    db 88
    db 3    ; Index to an effect block.
    db 62 + 3 * 64    ; Optimized wait for 5 lines.

    db 88
    db 0    ; Index to an effect block.
    db 62 + 1 * 64    ; Optimized wait for 3 lines.

    db 85
    db 6    ; Index to an effect block.
    db 62 + 3 * 64    ; Optimized wait for 5 lines.

    db 85
    db 3    ; Index to an effect block.
    db 62 + 3 * 64    ; Optimized wait for 5 lines.

    db 85
    db 0    ; Index to an effect block.
    db 62 + 3 * 64    ; Optimized wait for 5 lines.

    db 85
    db 5    ; Index to an effect block.
    db 62 + 3 * 64    ; Optimized wait for 5 lines.

    db 124    ; No note, but effects.
    db 13    ; Index to an effect block.
    db 124    ; No note, but effects.
    db 14    ; Index to an effect block.
    db 124    ; No note, but effects.
    db 18    ; Index to an effect block.
    db 124    ; No note, but effects.
    db 19    ; Index to an effect block.
    db 192
    db 0    ; New Instrument (0).
    db 1    ; Index to an effect block.
    db 61
    db 127    ; Waits for 128 lines.


Subsong0_Track15
    db 132
    db 4    ; New Instrument (4).
    db 61
    db 12    ; Waits for 13 lines.

    db 132
    db 5    ; New Instrument (5).
    db 61
    db 12    ; Waits for 13 lines.

    db 132
    db 4    ; New Instrument (4).
    db 62 + 0 * 64    ; Optimized wait for 2 lines.

    db 132
    db 5    ; New Instrument (5).
    db 130
    db 4    ; New Instrument (4).
    db 61
    db 12    ; Waits for 13 lines.

    db 130
    db 5    ; New Instrument (5).
    db 61
    db 127    ; Waits for 128 lines.


Subsong0_Track16
    db 220
    db 1    ; New Instrument (1).
    db 16    ; Index to an effect block.
    db 60    ; Waits for 1 line.

    db 99
    db 0    ; Index to an effect block.
    db 60    ; Waits for 1 line.

    db 104
    db 3    ; Index to an effect block.
    db 60    ; Waits for 1 line.

    db 107
    db 1    ; Index to an effect block.
    db 60    ; Waits for 1 line.

    db 92
    db 0    ; Index to an effect block.
    db 60    ; Waits for 1 line.

    db 99
    db 0    ; Index to an effect block.
    db 60    ; Waits for 1 line.

    db 104
    db 3    ; Index to an effect block.
    db 60    ; Waits for 1 line.

    db 107
    db 1    ; Index to an effect block.
    db 60    ; Waits for 1 line.

    db 92
    db 0    ; Index to an effect block.
    db 60    ; Waits for 1 line.

    db 99
    db 0    ; Index to an effect block.
    db 60    ; Waits for 1 line.

    db 104
    db 3    ; Index to an effect block.
    db 60    ; Waits for 1 line.

    db 107
    db 1    ; Index to an effect block.
    db 60    ; Waits for 1 line.

    db 92
    db 0    ; Index to an effect block.
    db 60    ; Waits for 1 line.

    db 99
    db 0    ; Index to an effect block.
    db 60    ; Waits for 1 line.

    db 104
    db 3    ; Index to an effect block.
    db 60    ; Waits for 1 line.

    db 107
    db 1    ; Index to an effect block.
    db 60    ; Waits for 1 line.

    db 90
    db 0    ; Index to an effect block.
    db 60    ; Waits for 1 line.

    db 94
    db 0    ; Index to an effect block.
    db 60    ; Waits for 1 line.

    db 102
    db 3    ; Index to an effect block.
    db 60    ; Waits for 1 line.

    db 106
    db 1    ; Index to an effect block.
    db 60    ; Waits for 1 line.

    db 90
    db 0    ; Index to an effect block.
    db 60    ; Waits for 1 line.

    db 94
    db 0    ; Index to an effect block.
    db 60    ; Waits for 1 line.

    db 102
    db 3    ; Index to an effect block.
    db 60    ; Waits for 1 line.

    db 106
    db 1    ; Index to an effect block.
    db 60    ; Waits for 1 line.

    db 90
    db 0    ; Index to an effect block.
    db 60    ; Waits for 1 line.

    db 94
    db 0    ; Index to an effect block.
    db 60    ; Waits for 1 line.

    db 102
    db 3    ; Index to an effect block.
    db 60    ; Waits for 1 line.

    db 106
    db 1    ; Index to an effect block.
    db 60    ; Waits for 1 line.

    db 90
    db 0    ; Index to an effect block.
    db 60    ; Waits for 1 line.

    db 94
    db 0    ; Index to an effect block.
    db 60    ; Waits for 1 line.

    db 102
    db 3    ; Index to an effect block.
    db 60    ; Waits for 1 line.

    db 106
    db 1    ; Index to an effect block.
    db 61
    db 127    ; Waits for 128 lines.


Subsong0_Track17
    db 239
    db 6    ; New Instrument (6).
    db 22    ; Index to an effect block.
    db 61
    db 14    ; Waits for 15 lines.

    db 43
    db 61
    db 14    ; Waits for 15 lines.

    db 42
    db 61
    db 6    ; Waits for 7 lines.

    db 45
    db 61
    db 14    ; Waits for 15 lines.

    db 42
    db 61
    db 127    ; Waits for 128 lines.


Subsong0_Track18
    db 171
    db 6    ; New Instrument (6).
    db 62 + 3 * 64    ; Optimized wait for 5 lines.

    db 124    ; No note, but effects.
    db 23    ; Index to an effect block.
    db 60    ; Waits for 1 line.

    db 47
    db 61
    db 22    ; Waits for 23 lines.

    db 124    ; No note, but effects.
    db 1    ; Index to an effect block.
    db 124    ; No note, but effects.
    db 3    ; Index to an effect block.
    db 124    ; No note, but effects.
    db 0    ; Index to an effect block.
    db 124    ; No note, but effects.
    db 5    ; Index to an effect block.
    db 124    ; No note, but effects.
    db 12    ; Index to an effect block.
    db 124    ; No note, but effects.
    db 13    ; Index to an effect block.
    db 124    ; No note, but effects.
    db 17    ; Index to an effect block.
    db 124    ; No note, but effects.
    db 14    ; Index to an effect block.
    db 124    ; No note, but effects.
    db 24    ; Index to an effect block.
    db 124    ; No note, but effects.
    db 25    ; Index to an effect block.
    db 124    ; No note, but effects.
    db 26    ; Index to an effect block.
    db 124    ; No note, but effects.
    db 18    ; Index to an effect block.
    db 124    ; No note, but effects.
    db 27    ; Index to an effect block.
    db 124    ; No note, but effects.
    db 28    ; Index to an effect block.
    db 124    ; No note, but effects.
    db 19    ; Index to an effect block.
    db 124    ; No note, but effects.
    db 29    ; Index to an effect block.
    db 192
    db 0    ; New Instrument (0).
    db 1    ; Index to an effect block.
    db 61
    db 127    ; Waits for 128 lines.


Subsong0_Track19
    db 239
    db 6    ; New Instrument (6).
    db 22    ; Index to an effect block.
    db 61
    db 14    ; Waits for 15 lines.

    db 43
    db 61
    db 14    ; Waits for 15 lines.

    db 50
    db 62 + 3 * 64    ; Optimized wait for 5 lines.

    db 52
    db 62 + 3 * 64    ; Optimized wait for 5 lines.

    db 54
    db 61
    db 127    ; Waits for 128 lines.


Subsong0_Track20
    db 183
    db 6    ; New Instrument (6).
    db 62 + 3 * 64    ; Optimized wait for 5 lines.

    db 54
    db 62 + 3 * 64    ; Optimized wait for 5 lines.

    db 52
    db 62 + 1 * 64    ; Optimized wait for 3 lines.

    db 47
    db 61
    db 14    ; Waits for 15 lines.

    db 124    ; No note, but effects.
    db 1    ; Index to an effect block.
    db 124    ; No note, but effects.
    db 3    ; Index to an effect block.
    db 124    ; No note, but effects.
    db 0    ; Index to an effect block.
    db 124    ; No note, but effects.
    db 5    ; Index to an effect block.
    db 124    ; No note, but effects.
    db 12    ; Index to an effect block.
    db 124    ; No note, but effects.
    db 13    ; Index to an effect block.
    db 124    ; No note, but effects.
    db 17    ; Index to an effect block.
    db 124    ; No note, but effects.
    db 14    ; Index to an effect block.
    db 124    ; No note, but effects.
    db 24    ; Index to an effect block.
    db 124    ; No note, but effects.
    db 25    ; Index to an effect block.
    db 124    ; No note, but effects.
    db 26    ; Index to an effect block.
    db 124    ; No note, but effects.
    db 18    ; Index to an effect block.
    db 124    ; No note, but effects.
    db 27    ; Index to an effect block.
    db 124    ; No note, but effects.
    db 28    ; Index to an effect block.
    db 124    ; No note, but effects.
    db 19    ; Index to an effect block.
    db 124    ; No note, but effects.
    db 29    ; Index to an effect block.
    db 192
    db 0    ; New Instrument (0).
    db 1    ; Index to an effect block.
    db 61
    db 127    ; Waits for 128 lines.


; The speed tracks
Subsong0_SpeedTrack0
    db 255    ; Wait for 128 lines.

; The event tracks
Subsong0_EventTrack0
    db 255    ; Wait for 128 lines.

Subsong0_DisarkByteRegionEnd0
